-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR AND INGREDIENT_TYPE = 'fruit_based'
GROUP BY FIRST_HALF.FLAVOR
HAVING SUM(TOTAL_ORDER) > 3000